sonar.projectKey=ticket-booking-app
sonar.projectName=Ticket Booking App
sonar.sources=backend,frontend/src,mobile/src
sonar.tests=backend/__tests__
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/*.log,backend/.env
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info
sonar.sourceEncoding=UTF-8
